const SNEAKERS = [
  {
    id: 1,
    name: "Nike Ja 3",
    brand: "Nike",
    model: "Ja 3",
    price: 22990,
    oldPrice: null,
    image: "images/sneakers/nike-ja3-1.png",
    colorway: "Iron Grey / Blue Void / White",
    color: "#4a5568",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: true,
    isHit: false,
    description: "Третья сигнатурная модель Джа Моранта — взрывная динамика, стильный дизайн и невероятная амортизация для доминирования на паркете.",
    history: "Линейка Nike Ja появилась в 2023 году как сигнатурная серия Джа Моранта — одного из самых взрывных разыгрывающих НБА. Ja 3 продолжает традицию создания лёгких, отзывчивых баскетбольных кроссовок с акцентом на вертикальную прыгучесть и быстроту первого шага. Модель стала хитом среди молодых игроков благодаря яркой эстетике и игровой универсальности.",
    technologies: "Zoom Air в передней части стопы обеспечивает мгновенный возврат энергии при каждом прыжке. Верх из-engineered mesh с усиленными зонами поддерживает стопу при резких сменах направления. Формованная межподошва из foam-материала дополняет амортизацию, а подоплёва с multidirectional traction даёт сцепление на любой поверхности.",
    specifications: {
      "Верх": "Engineered Mesh",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина с multidirectional traction",
      "Высота": "Mid-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "HF2793-601",
      "Игрок": "Ja Morant"
    }
  },
  {
    id: 2,
    name: "Jordan Tatum 4",
    brand: "Jordan",
    model: "Tatum 4",
    price: 15990,
    oldPrice: null,
    image: "images/sneakers/jordan-tatum4-1.png",
    colorway: "Black / Pink Blast / White",
    color: "#1a1a2e",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: true,
    isHit: true,
    description: "Четвёртая сигнатурная модель Джейсона Тейтума — элегантность, мощь и бескомпромиссная игровая производительность от Jordan Brand.",
    history: "Серия Tatum от Jordan Brand дебютировала в 2023 году и быстро стала одной из самых востребованных сигнатурных линеек. Джейсон Тейтум — суперзвезда Boston Celtics, чемпион НБА 2024 года. Tatum 4 создан для универсального нападающего, который одинаково опасен и с трёхочковой дистанции, и при проходе к кольцу.",
    technologies: "Zoom Air карманы расположены стратегически для максимальной отзывчивости. Лёгкий плетёный верх с бесшовными накладками обеспечивает вентиляцию и поддержку. Система шнуровки интегрирована с боковыми рамками для фиксации стопы. Подоплёва с круговым рисунком протектора гарантирует сцепление при любых манёврах.",
    specifications: {
      "Верх": "Woven Mesh + бесшовные накладки",
      "Межподошва": "Zoom Air",
      "Подоплёва": "Резиновая, круговой протектор",
      "Высота": "Mid-top",
      "Вес": "~330 г (размер 42)",
      "Артикул": "GS модель",
      "Игрок": "Jayson Tatum"
    }
  },
  {
    id: 3,
    name: "Nike Ja 3",
    brand: "Nike",
    model: "Ja 3",
    price: 22990,
    oldPrice: null,
    image: "images/sneakers/nike-ja3-2.jpg",
    colorway: "Pink Lemonade / Volt",
    color: "#e84393",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: true,
    description: "Nike Ja 3 в яркой расцветке Pink Lemonade — для тех, кто хочет выделяться на паркете и за его пределами.",
    history: "Линейка Nike Ja появилась в 2023 году как сигнатурная серия Джа Моранта. Ja 3 продолжает традицию создания лёгких, отзывчивых баскетбольных кроссовок с акцентом на вертикальную прыгучесть и быстроту первого шага. Эта расцветка вдохновлена летней игрой и уличным стилем Мемфиса.",
    technologies: "Zoom Air в передней части стопы обеспечивает мгновенный возврат энергии. Верх из engineered mesh с усиленными зонами поддерживает стопу при резких сменах направления. Формованная межподошва дополняет амортизацию, а подоплёва с multidirectional traction даёт надёжное сцепление.",
    specifications: {
      "Верх": "Engineered Mesh",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина с multidirectional traction",
      "Высота": "Mid-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "HF2793-601",
      "Игрок": "Ja Morant"
    }
  },
  {
    id: 4,
    name: "Nike KD 18",
    brand: "Nike",
    model: "KD 18",
    price: 19990,
    oldPrice: null,
    image: "images/sneakers/nike-kd18-1.jpg",
    colorway: "Seat Pleasant / Blue / Neon Green",
    color: "#2d6cdf",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: true,
    isHit: false,
    description: "18-я сигнатурная модель Кевина Дюранта — непревзойдённая плавность хода и точность для элитного скорера.",
    history: "Серия KD — одна из самых длинных сигнатурных линеек в истории Nike, стартовавшая в 2009 году. KD 18 назван в честь родного города Дюранта — Seat Pleasant, Мэриленд. Кевин Дюрант — один из величайших скореров в истории НБА, и каждая его модель отражает его стиль: плавный, результативный и неукротимый.",
    technologies: "Dual Zoom Air блоки в пяточной и носочной зонах создают двойную амортизацию для плавных приземлений. Верх из лёгкого mesh-материала с динамическими Flywire нитями обхватывает стопу. Средняя подошва из мягкого foam обеспечивает плавный перекат, а подоплёва с продольным и поперечным протектором даёт сцепление при рывках.",
    specifications: {
      "Верх": "Mesh + Flywire",
      "Межподошва": "Dual Zoom Air + Foam",
      "Подоплёва": "Резина, multidirectional",
      "Высота": "Low-top",
      "Вес": "~350 г (размер 42)",
      "Артикул": "HV1992-400",
      "Игрок": "Kevin Durant"
    }
  },
  {
    id: 5,
    name: "Nike Ja 3",
    brand: "Nike",
    model: "Ja 3",
    price: 22990,
    oldPrice: null,
    image: "images/sneakers/nike-ja3-3.jpg",
    colorway: "Sunset Tint / Coral",
    color: "#e17055",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: false,
    description: "Nike Ja 3 в расцветке Sunset Tint — тёплые закатные тона для яркой игры и стильного образа.",
    history: "Линейка Nike Ja появилась в 2023 году как сигнатурная серия Джа Моранта. Эта расцветка Sunset Tint вдохновлена закатами над Мемфисом и уличной культурой юга США. Ja 3 создан для динамичного стиля игры с акцентом на взрывные прыжки и быстрые прорывы.",
    technologies: "Zoom Air в передней части стопы обеспечивает мгновенный возврат энергии при каждом прыжке. Верх из engineered mesh с усиленными зонами поддерживает стопу при резких сменах направления. Формованная межподошва дополняет амортизацию.",
    specifications: {
      "Верх": "Engineered Mesh",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина с multidirectional traction",
      "Высота": "Mid-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "HF2794-601",
      "Игрок": "Ja Morant"
    }
  },
  {
    id: 6,
    name: "Nike LeBron XXIII",
    brand: "Nike",
    model: "LeBron XXIII",
    price: 29990,
    oldPrice: null,
    image: "images/sneakers/nike-lebron23-1.jpg",
    colorway: "White / University Red",
    color: "#c0392b",
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: true,
    isHit: true,
    description: "23-я сигнатурная модель Леброна Джеймса — легенда продолжается, премиальная амортизация и мощь для доминирования.",
    history: "Серия LeBron — самая знаковая сигнатурная линейка в истории баскетбола. LeBron XXIII — дань уважения номеру 23, под которым Леброн провёл большую часть своей легендарной карьеры. Каждая модель серии эволюционировала вместе с игрой Джеймса, и 23-я версия — вершина технологичности и стиля.",
    technologies: "Max Air в пяточной части в сочетании с Zoom Air в носочной обеспечивают двухуровневую амортизацию для мощных приземлений и быстрых рывков. KnitPosite 2.0 верх сочетает эластичность knit и прочность синтетических волокон. Карбоновая пластина в средней части стопы обеспечивает торсионную жёсткость.",
    specifications: {
      "Верх": "KnitPosite 2.0",
      "Межподошва": "Max Air + Zoom Air",
      "Подоплёва": "Резина, herringbone",
      "Высота": "Mid-top",
      "Вес": "~420 г (размер 42)",
      "Артикул": "IB9563-100",
      "Игрок": "LeBron James"
    }
  },
  {
    id: 7,
    name: "Nike Freak 7",
    brand: "Nike",
    model: "Freak 7",
    price: 21990,
    oldPrice: null,
    image: "images/sneakers/nike-freak7-1.jpg",
    colorway: "White / Orange / Volt",
    color: "#f39c12",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: true,
    isHit: false,
    description: "Седьмая сигнатурная модель Янниса Адетокунбо — европейская мощь, греческая мифология и бесконечная энергия на паркете.",
    history: "Серия Freak началась в 2019 году и стала одной из самых популярных доступных сигнатурных линеек Nike. Яннис Адетокунбо — двукратный MVP НБА, чемпион 2021 года с Milwaukee Bucks. Freak 7 продолжает традицию создания мощных, амортизирующих кроссовок для игроков, которые атакуют кольцо изо всех сил.",
    technologies: "Zoom Air в носочной части для отзывчивости при прыжках. Мягкая foam межподошва для комфортной амортизации. Широкая подоплёва с агрессивным протектором для сцепления при мощных рывках. Верх из прочного mesh с накладками для поддержки стопы.",
    specifications: {
      "Верх": "Mesh + синтетические накладки",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина, агрессивный протектор",
      "Высота": "Mid-top",
      "Вес": "~370 г (размер 42)",
      "Артикул": "HF3451-100",
      "Игрок": "Giannis Antetokounmpo"
    }
  },
  {
    id: 8,
    name: "Nike Ja 3",
    brand: "Nike",
    model: "Ja 3",
    price: 22990,
    oldPrice: null,
    image: "images/sneakers/nike-ja3-4.jpg",
    colorway: "Pink Foam / Orange",
    color: "#fd79a8",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: false,
    description: "Nike Ja 3 в розово-оранжевой расцветке — свежий взгляд на сигнатурную модель Джа Моранта для стильных игроков.",
    history: "Линейка Nike Ja появилась в 2023 году. Эта расцветка Pink Foam / Orange продолжает традицию ярких цветовых решений серии. Джа Морант известен не только своей взрывной игрой, но и любовью к ярким кроссовкам, и этот вариант идеально отражает его стиль.",
    technologies: "Zoom Air в передней части стопы для отзывчивости. Mesh верх с усиленными зонами для поддержки. Формованная foam межподошва для амортизации. Multidirectional traction подоплёва для надёжного сцепления.",
    specifications: {
      "Верх": "Engineered Mesh",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина с multidirectional traction",
      "Высота": "Mid-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "HF2794-201",
      "Игрок": "Ja Morant"
    }
  },
  {
    id: 9,
    name: "Nike Ja 3",
    brand: "Nike",
    model: "Ja 3",
    price: 22990,
    oldPrice: null,
    image: "images/sneakers/nike-ja3-5.jpg",
    colorway: "Black / White / Atomic Green",
    color: "#00b894",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: true,
    description: "Nike Ja 3 в расцветке Atomic Green — сдержанный чёрный баз с яркими зелёными акцентами для дерзкой игры.",
    history: "Линейка Nike Ja — сигнатурная серия Джа Моранта с 2023 года. Расцветка Atomic Green вдохновлена неоновыми огнями ночного Мемфиса. Чёрно-белая основа с зелёными акцентами — для тех, кто предпочитает сдержанный стиль с яркими деталями.",
    technologies: "Zoom Air в передней части стопы обеспечивает отзывчивость при каждом прыжке. Mesh верх с зонами поддержки для стабильности при смене направления. Foam межподошва и multidirectional traction подоплёва.",
    specifications: {
      "Верх": "Engineered Mesh",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина с multidirectional traction",
      "Высота": "Mid-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "IH0797-100",
      "Игрок": "Ja Morant"
    }
  },
  {
    id: 10,
    name: "Nike KD 18",
    brand: "Nike",
    model: "KD 18",
    price: 19990,
    oldPrice: null,
    image: "images/sneakers/nike-kd18-2.jpg",
    colorway: "Blue Void / White / Volt",
    color: "#0984e3",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: true,
    description: "Nike KD 18 в классической расцветке Blue Void — премиальная амортизация и плавность для элитного скорера.",
    history: "KD 18 продолжает легендарную серию сигнатурных кроссовок Кевина Дюранта. Серия стартовала в 2009 году и прошла путь от революционного KD I до технологичного KD 18. Эта расцветка Blue Void — классическое сочетание синего и белого с неоновыми акцентами Volt.",
    technologies: "Dual Zoom Air для двойной амортизации. Mesh верх с Flywire нитями для фиксации стопы. Мягкая foam межподошва для плавного переката. Резиновая подоплёва с multidirectional протектором.",
    specifications: {
      "Верх": "Mesh + Flywire",
      "Межподошва": "Dual Zoom Air + Foam",
      "Подоплёва": "Резина, multidirectional",
      "Высота": "Low-top",
      "Вес": "~350 г (размер 42)",
      "Артикул": "HV1992-100",
      "Игрок": "Kevin Durant"
    }
  },
  {
    id: 11,
    name: "Jordan Tatum 4",
    brand: "Jordan",
    model: "Tatum 4",
    price: 15990,
    oldPrice: null,
    image: "images/sneakers/jordan-tatum4-2.jpg",
    colorway: "White / Black / Gym Red",
    color: "#e74c3c",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: false,
    description: "Jordan Tatum 4 в классической расцветке Bulls — красно-чёрно-белое трио цветов величайшей династии НБА.",
    history: "Серия Tatum от Jordan Brand — одна из самых молодых и динамичных сигнатурных линеек. Джейсон Тейтум привёл Boston Celtics к чемпионству в 2024 году, и Tatum 4 создавался уже с учётом его статуса чемпиона. Расцветка White/Black/Gym Red отдаёт дань уважения цветам Chicago Bulls и наследию Джордана.",
    technologies: "Zoom Air карманы для отзывчивости. Плетёный верх с бесшовными накладками для вентиляции. Интегрированная система шнуровки с боковыми рамками для фиксации. Круговой протектор подоплёвы для сцепления.",
    specifications: {
      "Верх": "Woven Mesh + бесшовные накладки",
      "Межподошва": "Zoom Air",
      "Подоплёва": "Резина, круговой протектор",
      "Высота": "Mid-top",
      "Вес": "~330 г (размер 42)",
      "Артикул": "GS модель",
      "Игрок": "Jayson Tatum"
    }
  },
  {
    id: 12,
    name: "Jordan Luka 77",
    brand: "Jordan",
    model: "Luka 77",
    price: 15990,
    oldPrice: null,
    image: "images/sneakers/jordan-luka77-1.jpg",
    colorway: "Particle Grey / White",
    color: "#b2bec3",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: false,
    description: "Jordan Luka 77 — сигнатурная модель Луки Дончича, магия европейского баскетбола в каждом движении.",
    history: "Лука Дончич — феномен из Словении, который перевернул представление о европейском баскетболе в НБА. Luka 77 — его сигнатурная линейка от Jordan Brand, где число 77 — его игровой номер. Модель создана для.playmaker'а, который видит площадку как шахматную доску и делает невозможные передачи обычным делом.",
    technologies: "Zoom Air в носочной части для отзывчивости при рывках. Мягкая foam межподошва для комфорта при долгой игре. Прочный верх из mesh и синтетических материалов для поддержки. Широкая подоплёва для стабильности.",
    specifications: {
      "Верх": "Mesh + синтетические накладки",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина, широкий протектор",
      "Высота": "Low-top",
      "Вес": "~350 г (размер 42)",
      "Артикул": "HF0806-002",
      "Игрок": "Luka Doncic"
    }
  },
  {
    id: 13,
    name: "Nike Freak 7",
    brand: "Nike",
    model: "Freak 7",
    price: 21990,
    oldPrice: null,
    image: "images/sneakers/nike-freak7-2.jpg",
    colorway: "Obsidian / Teal / Gold / Orange",
    color: "#6c5ce7",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: true,
    description: "Nike Freak 7 в яркой расцветке Obsidian/Teal — греческий миф на баскетбольном паркете в каждом прыжке.",
    history: "Серия Freak — сигнатурная линейка Янниса Адетокунбо от Nike с 2019 года. Freak 7 — новейшая версия, созданная для мощного форварда, который играет как центровой, но двигается как разыгрывающий. Расцветка Obsidian/Teal вдохновлена греческим наследием Янниса.",
    technologies: "Zoom Air в носочной части для отзывчивости. Мягкая foam межподошва для амортизации. Прочный mesh верх с накладками для поддержки. Широкая подоплёва с агрессивным протектором для сцепления.",
    specifications: {
      "Верх": "Mesh + синтетические накладки",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина, агрессивный протектор",
      "Высота": "Mid-top",
      "Вес": "~370 г (размер 42)",
      "Артикул": "HF3451-005",
      "Игрок": "Giannis Antetokounmpo"
    }
  },
  {
    id: 14,
    name: "Jordan Luka 5",
    brand: "Jordan",
    model: "Luka 5",
    price: 16990,
    oldPrice: null,
    image: "images/sneakers/jordan-luka5-1.png",
    colorway: "Black / White",
    color: "#2d3436",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: false,
    isHit: false,
    description: "Jordan Luka 5 в классической чёрно-белой расцветке — минимализм и магия Луки Дончича в чистом виде.",
    history: "Luka 5 — пятая сигнатурная модель Луки Дончича от Jordan Brand. Дончич — один из самых талантливых и креативных игроков современного НБА, чемпион НБА 2024 года. Luka 5 создавался для playmaker'а, который контролирует темп игры и создаёт моменты из ничего.",
    technologies: "Zoom Air для отзывчивости. Формованная foam межподошва для плавного переката. Mesh верх с бесшовными зонами для комфорта. Подоплёва с круговым протектором для манёвренности.",
    specifications: {
      "Верх": "Mesh + бесшовные зоны",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина, круговой протектор",
      "Высота": "Low-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "IU2366-900",
      "Игрок": "Luka Doncic"
    }
  },
  {
    id: 15,
    name: "Jordan Luka 5",
    brand: "Jordan",
    model: "Luka 5",
    price: 16990,
    oldPrice: null,
    image: "images/sneakers/jordan-luka5-2.jpg",
    colorway: "Blue Tint / Orange / Light Menta",
    color: "#74b9ff",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    category: "basketball",
    isNew: true,
    isHit: false,
    description: "Jordan Luka 5 в яркой расцветке Blue Tint — свежие цвета для магического стиля игры Луки Дончича.",
    history: "Luka 5 — пятая сигнатурная модель Луки Дончича от Jordan Brand. Эта расцветка Blue Tint / Orange вдохновлена летним стилем и свободой творчества на площадке. Дончич известен своей непредсказуемой игрой, и эта цветовая схема отражает его креативность.",
    technologies: "Zoom Air для отзывчивости при рывках и прыжках. Формованная foam межподошва для комфорта. Mesh верх с бесшовными зонами для вентиляции и поддержки. Подоплёва с круговым протектором.",
    specifications: {
      "Верх": "Mesh + бесшовные зоны",
      "Межподошва": "Zoom Air + Foam",
      "Подоплёва": "Резина, круговой протектор",
      "Высота": "Low-top",
      "Вес": "~340 г (размер 42)",
      "Артикул": "IU2366-900",
      "Игрок": "Luka Doncic"
    }
  }
];

const BRANDS = [
  { name: "Nike", logo: "Nike", color: "#111" },
  { name: "Jordan", logo: "Jordan", color: "#1a1a2e" }
];

const SIZES = [38, 39, 40, 41, 42, 43, 44, 45, 46];
